
package edu.buaa.nlp.ws.client.dataProvider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataService", targetNamespace = "http://service.nlp.buaa.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DataService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.nlp.buaa.edu/DataService/fetchDataRequest", output = "http://service.nlp.buaa.edu/DataService/fetchDataResponse")
    public String fetchData(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    String arg2);

}
