
package edu.buaa.nlp.ws.client.dataProvider;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataServiceImpl", targetNamespace = "http://impl.service.nlp.buaa.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchData", targetNamespace = "http://impl.service.nlp.buaa.edu/", className = "edu.buaa.nlp.ws.client.dataProvider.FetchData")
    @ResponseWrapper(localName = "fetchDataResponse", targetNamespace = "http://impl.service.nlp.buaa.edu/", className = "edu.buaa.nlp.ws.client.dataProvider.FetchDataResponse")
    @Action(input = "http://impl.service.nlp.buaa.edu/DataServiceImpl/fetchDataRequest", output = "http://impl.service.nlp.buaa.edu/DataServiceImpl/fetchDataResponse")
    public String fetchData();

}
