
package edu.buaa.nlp.ws.client.dataProvider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import controller.Constants;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataServiceImplService", targetNamespace = "http://impl.service.nlp.buaa.edu/", wsdlLocation = "http://192.168.55.136:10005/DataProvider?wsdl")
public class DataServiceImplService
    extends Service
{

    private final static URL DATASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DATASERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.nlp.buaa.edu/", "DataServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.DATA_CONTROLLER_URL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DATASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DataServiceImplService() {
        super(__getWsdlLocation(), DATASERVICEIMPLSERVICE_QNAME);
    }

    public DataServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATASERVICEIMPLSERVICE_QNAME, features);
    }

    public DataServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DATASERVICEIMPLSERVICE_QNAME);
    }

    public DataServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATASERVICEIMPLSERVICE_QNAME, features);
    }

    public DataServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataService
     */
    @WebEndpoint(name = "DataServiceImplPort")
    public DataService getDataServiceImplPort() {
        return super.getPort(new QName("http://impl.service.nlp.buaa.edu/", "DataServiceImplPort"), DataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataService
     */
    @WebEndpoint(name = "DataServiceImplPort")
    public DataService getDataServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.nlp.buaa.edu/", "DataServiceImplPort"), DataService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DATASERVICEIMPLSERVICE_EXCEPTION;
        }
        return DATASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
